### ISSUE TITLE
Add flag for latest prusaslicer build

### ISSUE THREAD

**Issue by longman391** [dmagyar/prusaslicer-vnc-docker#1]
Currently, I don't think there's a way to set a flag to pull the "latest" tagged build of prusaslicer. This means that when you need to run the latest version, even if it's a RC or beta, there's no way to do it automatically. Using "latest" on the container just pulls the latest version of this container, not prusaslicer itself.

It would be great to add a flag to pull the latest version of prusaslicer and/or to specify a particular version/build of prusaslicer to pull.

**Comment by dmagyar** [comment]
Good suggestion! Check out the fresh commit and container that updates to the latest Prusaslicer on every start - unless your specify OVERRIDE_SLICER_URL in env to stick to a given version.

**Comment by longman391** [comment]
This is great, and better than the PR I was going to suggest. Thanks much!
